script: 'bundle exec rake test'
language: ruby
before_install:
  - sudo add-apt-repository -y "ppa:adrian-wilkins/kyoto-cabinet"
  - sudo apt-get update
  - sudo apt-get install kyotocabinet
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - rbx-2
  - jruby
  - jruby-head
  - ruby-head
cache: bundler
